# Generated by Django 4.2.23 on 2025-06-27 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hindi_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hindi_name', models.CharField(blank=True, max_length=100)),
                ('npk_ratio', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('application_rate', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organic_fertilizer', models.CharField(blank=True, max_length=200)),
                ('application_timing', models.TextField(blank=True)),
                ('special_notes', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer.crop')),
                ('primary_fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_recommendations', to='fertilizer.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hindi_name', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hindi_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFertilizerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer.crop')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilizer.fertilizerrecommendation')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer.region')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer.soiltype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer.region'),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='secondary_fertilizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_recommendations', to='fertilizer.fertilizer'),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='soil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer.soiltype'),
        ),
    ]
