# Generated by Django 5.0.2 on 2025-06-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='audio_en',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='audio_hi',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='gemini_response',
            field=models.TextField(blank=True),
        ),
    ]
